### ISSUE TITLE
Untranslated points

### ISSUE THREAD

**Issue by weldonsantos** [frappe/crm#138]
I inserted all the keywords for translation and there were some that were not translated, as shown in the images

<img width="813" alt="image" src="https://github.com/frappe/crm/assets/72267543/fa20e7c1-e9a7-4e97-83e2-e3529538fcbb">

<img width="835" alt="image" src="https://github.com/frappe/crm/assets/72267543/3b9b87ae-adf8-4c75-8ae7-22bea17e6d68">

<img width="658" alt="image" src="https://github.com/frappe/crm/assets/72267543/e3877420-1d4e-4806-a03c-7174efbd1df6">

<img width="1326" alt="image" src="https://github.com/frappe/crm/assets/72267543/565e801c-560e-4a20-a12b-a6ec96123863">

<img width="1213" alt="image" src="https://github.com/frappe/crm/assets/72267543/c5ecd4fc-2e30-41af-90de-4d7dc1dfbe0c">

**Comment by shariquerik** [comment]
<img width="618" alt="image" src="https://github.com/frappe/crm/assets/30859809/57daceb7-bddf-47ad-b52e-416b5efe885b">

@weldonsantos in this "New" & "Qualified" are data not label or static text and these values are coming from CRM Lead Source & CRM Deal Source you can always add your own already translated statuses there or rename existing ones.

I checked in the above image you also highlighted "from" but I checked it is getting translated
<img width="466" alt="image" src="https://github.com/frappe/crm/assets/30859809/c0f61bf2-1057-4cb1-9897-72388c1774e1">

On the Contact & Organization page "Mobile no" & Deal owner" are also working. I think you missed that "n" in Mobile no is small and "o" in Deal owner is small. You will have to create a separate translation for them.
<img width="1211" alt="image" src="https://github.com/frappe/crm/assets/30859809/a9a0fdb2-2c83-4727-a4b0-b8d460ef1513">


Rest I have fixed
PR: https://github.com/frappe/crm/pull/137
commit: https://github.com/frappe/crm/commit/e04a4c6b4c1381040efb887de7681512c996cb15

**Comment by weldonsantos** [comment]
The points I brought, I was able to translate here, thank you

I missed these that I couldn't get

![image](https://github.com/frappe/crm/assets/72267543/4d349d56-c9f9-40c0-b204-a4041b203dc6)

![image](https://github.com/frappe/crm/assets/72267543/e9142e81-66be-4abf-9180-377a833e2880)


Can you tell me how I can translate this?
![image](https://github.com/frappe/crm/assets/72267543/37c724c9-6f1a-4a0f-9da3-5bbba9491f6f)

**Comment by shariquerik** [comment]
@weldonsantos Can you create a new issue with above mentioned issue
The login screen is simple fix I will do
The time translation I will have to figure out better solution for that
Just create a new Issue it will be easy to track
