### ISSUE TITLE
When Deal is created contact is not creating automatically.

### ISSUE THREAD

**Issue by jyotigujjarisamsoft** [frappe/crm#149]
When Deal is created contact is not creating automatically. Every time i need to click on create contact and again has to create contact for that deal.

**Comment by shariquerik** [comment]
@jyotigujjarisamsoft I am not able to reproduce the issue. Please add some screenshot or screen recording for better understanding

**Comment by jyotigujjarisamsoft** [comment]
When i create Deal contact also created automatically but in deal page in contact section only name is showing mobile number not showing.
![Screenshot from 2024-04-30 11-10-30](https://github.com/frappe/crm/assets/161429098/28a8eb68-0c26-458a-b875-3d4f832ed947)
![Screenshot from 2024-04-30 11-10-17](https://github.com/frappe/crm/assets/161429098/2b700747-effe-4306-97b4-062aaf8dbda7)

**Comment by shariquerik** [comment]
@jyotigujjarisamsoft On deal page click on the Contact name then you will see the email & contact number
<img width="349" alt="image" src="https://github.com/frappe/crm/assets/30859809/823760f0-73c0-4e7c-884d-f31dd0fc4f6a">
