### ISSUE TITLE
Contact number not showing after creating contact.

### ISSUE THREAD

**Issue by jyotigujjarisamsoft** [frappe/crm#151]
I tried to create new contact from deal.In dialog box i gave mobile number and all data.But on creation of contact mobile number not saving and not showing in deal.

**Comment by shariquerik** [comment]
@jyotigujjarisamsoft I am not able to reproduce the issue. Please add some screenshot or screen recording for better understanding also steps to reproduce the issue

**Comment by jyotigujjarisamsoft** [comment]
i added contact number but too not showing
![Screenshot from 2024-04-30 11-14-33](https://github.com/frappe/crm/assets/161429098/7016e0cc-86fb-4cd4-b7be-ec8ee0661081)
 if i add country code in number it will update in contact +91 but it is not showing in deal contact section.If i not add country code mobile number is not updating in contact also.Is that mandatory you made adding country code.If yes we have clients in dubai also for them how i need to give number ?

**Comment by jyotigujjarisamsoft** [comment]
![Screenshot from 2024-04-30 11-10-17](https://github.com/frappe/crm/assets/161429098/b7ed003a-f7cc-48e1-adbd-510b27b3d7e8)

**Comment by shariquerik** [comment]
@jyotigujjarisamsoft Country code is not mandatory and it is visible in deal you will have to click on Contact name to see the number
<img width="349" alt="image" src="https://github.com/frappe/crm/assets/30859809/3466e6f2-6920-4587-abed-d29141238d1d">
