### ISSUE TITLE
Mobile number issue in contact.

### ISSUE THREAD

**Issue by jyotigujjarisamsoft** [frappe/crm#152]
In contact doctype when i click on edit mobile number is dropdown,But if i create contact from deal mobile number is data type.Mobile number not able to update on creation of new and on edit.Need to do twice then only it will show.And in list view of contact also mobile number not shown .

**Comment by jyotigujjarisamsoft** [comment]
But we are giving mobile number while creating new contact right?
![Screenshot from 2024-04-29 14-19-33](https://github.com/frappe/crm/assets/161429098/60eff71d-9e23-4424-8b16-ac936a6025aa)

**Comment by jyotigujjarisamsoft** [comment]
In above we are giving mobile number but after save it is not saving and not showing in deal and contact.

**Comment by shariquerik** [comment]
@jyotigujjarisamsoft I tried replicating I was not able to.
Please attach screen recording of the issue and reopen the issue
