### ISSUE TITLE
A few bugs in CRM: multiple entries saved, default status

### ISSUE THREAD

**Issue by ajiragroup** [frappe/crm#161]
I encountered some bugs and I have shown it in video;

Bug 1: No default Status is set which causes lead form not being saved.
Bug 2: Popup does not auto-close when clicked outside.
Bug 3: Multiple entries of same lead are saved when clicked multiple times on Save button..

Here' my system apps version:

![image](https://github.com/frappe/crm/assets/108009061/62345c65-8725-4fa8-aa29-cb814ac274d4)

https://github.com/frappe/crm/assets/108009061/83bc67f2-4889-457a-b582-fdb6cc17e40e

**Comment by shariquerik** [comment]
> Bug 2: Popup does not auto-close when clicked outside.

@ajiragroup This is a Frappe UI bug not Frappe CRM rest I have fixed in linked PR

**Comment by ajiragroup** [comment]
> This is a Frappe UI bug not Frappe CRM

Could you transfer this issue to Frappe UI or do I have to create a new one there ?
