### ISSUE TITLE
Whatsapp message not live updating

### ISSUE THREAD

**Issue by nilpatel42** [frappe/crm#167]
whatsapp message not live updating, for new message we need switch the tabs or need to reload the browser tab

also notification for whatsapp message not showing (if implemented)

![image](https://github.com/frappe/crm/assets/135511086/9d9d953d-4a1b-4b8d-be30-5e3f69a4416d)

**Comment by shariquerik** [comment]
The screenshot doesn't help. Can you add a screen recording?
I have tested it in my instance it works fine.

**Comment by nilpatel42** [comment]
[screen-recorder-thu-may-02-2024-12-42-19_TkmZm9al.webm](https://github.com/frappe/crm/assets/135511086/f88d6fc8-1825-444a-b39a-180d20837638)

**Comment by shariquerik** [comment]
I cannot see any whatsapp template
To start the communication you will first have to send a whatsapp template and after sending template customer should reply then only conversation starts

To create a template go to WhatsApp Templates and create one then come here in lead page then click on send template you should be able to see the template send it and then reply from whatsapp
Now real-time should work

**Comment by nilpatel42** [comment]
I have message template, my template with variable not working, when i test with text only template, 
issues is same, 

also notification is only showing when i accessing the server via my domain or static ip, 
it's not showing when i access via local ip

https://github.com/frappe/crm/assets/135511086/e49a70de-d303-449c-9b04-e3623b4d72a9

**Comment by shariquerik** [comment]
@nilpatel42 Can you verify again if this still happening, because I am not able to reproduce it.
Check this video https://frappe.io/crm

**Comment by nilpatel42** [comment]
Still same, is there any other issue apart from crm app ?

> @nilpatel42 Can you verify again if this still happening, because I am not able to reproduce it. Check this video https://frappe.io/crm

I checked but still not updating, is there any other issue apart from crm app ?
