### ISSUE TITLE
Comments not rendering out all information added

### ISSUE THREAD

**Issue by neelbhanushali** [frappe/crm#168]
Following information was added 
1. Bold
2. Italic
3. Heading
4. Weblink
5. File Attachment

Following rendered out correctly
1. Bold
2. Italic
3. Weblink

Following had problem rendering out
1. Heading
2. File Attachment

Attaching a video for reference
[screen-capture.webm](https://github.com/frappe/crm/assets/29022906/865cc049-93b5-42bd-b954-520f8639f3f9)

**Comment by shariquerik** [comment]
Fix: https://github.com/frappe/crm/commit/3230e59643933a7116748052cb4661de315a79b2
