### ISSUE TITLE
Email templates using conditional statements are broken

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/crm#177]
This issue is mostly informational. Actual problem lies upstream in the Frappe repo at https://github.com/frappe/frappe/issues/26396.

Users should be aware that some recipients of their emails (primarily those using Outlook for Windows as their email client) might be receiving blank or partial emails if condtional statements were used in the templates.

**Comment by shariquerik** [comment]
It is Frappe framework issue so closing
