### ISSUE TITLE
Confusing crm experience

### ISSUE THREAD

**Issue by aghanem** [frappe/crm#187]
I created a trial CRM account (https://aghanem.frappe.cloud/crm), but then when I try to create a lead , there are several fields that I really didn't fill in advance and I don't know how to adjust per my country and domain.

![image](https://github.com/frappe/crm/assets/2403613/e9b34b8f-c5ef-4e28-b773-758fb27268c3)

even when switching to desk , I couldn't find from where the CRM brgint these values (e.g. India).
![image](https://github.com/frappe/crm/assets/2403613/90c748fd-4811-4afc-88c5-719fc697dd25)

**Comment by shariquerik** [comment]
@aghanem It is just a placeholder there is no value. You will have to add it from desk
