### ISSUE TITLE
HTML Email Templates have empty content when viewed via the Email Templates tab

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/crm#198]
![image](https://github.com/frappe/crm/assets/57280279/947104c6-99d9-48ae-8361-524a0b6fde7d)

The template actually has HTML content. It shows up as empty here.

**Comment by shariquerik** [comment]
@SvbZ3r0 Can share an example, so that I can replicate

**Comment by SvbZ3r0** [comment]
Created and saved email template here:
![image](https://github.com/frappe/crm/assets/57280279/6af96808-4d51-44a7-a377-d4a9abbb9d78)

Opened here:
![image](https://github.com/frappe/crm/assets/57280279/4fb62b6b-3d72-448d-9189-56f168da0641)

The content fields used when `use_html` is ticked and when it is not are different. One is `response` which I think is used by the CRM module and the other is `response_html` which the module ignores.
