### ISSUE TITLE
FCRM Exception: While changing status in Frappe CRM

### ISSUE THREAD

**Issue by arsalanmudni2** [frappe/crm#206]
https://github.com/frappe/crm/blob/e7ca90df51e99d29a41fba74e6b18f0b6642adc4/crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py#L30

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'","exc_type":"TypeError","exc_source":"crm (app)","exc":"[\"Traceback (most recent call last):\
  File \\\"apps/frappe/frappe/app.py\\\", line 110, in application\
    response = frappe.api.handle(request)\
  File \\\"apps/frappe/frappe/api/init.py\\\", line 49, in handle\
    data = endpoint(**arguments)\
  File \\\"apps/frappe/frappe/api/v1.py\\\", line 36, in handle_rpc_call\
    return frappe.handler.handle()\
  File \\\"apps/frappe/frappe/handler.py\\\", line 49, in handle\
    data = execute_cmd(cmd)\
  File \\\"apps/frappe/frappe/handler.py\\\", line 85, in execute_cmd\
    return frappe.call(method, **frappe.form_dict)\
  File \\\"apps/frappe/frappe/init_.py\\\", line 1768, in call\
    return fn(*args, **newargs)\
  File \\\"apps/frappe/frappe/utils/typing_validations.py\\\", line 31, in wrapper\
    return func(*args, **kwargs)\
  File \\\"apps/frappe/frappe/desk/form/save.py\\\", line 39, in savedocs\
    doc.save()\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 337, in save\
    return self._save(*args, **kwargs)\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 373, in _save\
    self.run_before_save_methods()\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 1091, in run_before_save_methods\
    self.run_method(\\\"validate\\\")\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 962, in run_method\
    out = Document.hook(fn)(self, *args, **kwargs)\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 1322, in composer\
    return composed(self, method, *args, **kwargs)\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 1304, in runner\
    add_to_return_value(self, fn(self, *args, **kwargs))\
  File \\\"apps/frappe/frappe/model/document.py\\\", line 959, in fn\
    return method_object(*args, **kwargs)\
  File \\\"apps/crm/crm/fcrm/doctype/crm_lead/crm_lead.py\\\", line 28, in validate\
    add_status_change_log(self)\
  File \\\"apps/crm/crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py\\\", line 30, in add_status_change_log\
    last_status_change.duration = (last_status_change.to_date - last_status_change.from_date).total_seconds()\
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'\

**Comment by shariquerik** [comment]
@arsalanmudni2 Add steps to reproduce the above description doesnt help

**Comment by arsalanmudni2** [comment]
Steps to Reproduce:
Go to CRM Lead List.
Add New CRM Lead
Select the Lead.
Go to Other Tab, change the status and save.
I have also attached screenshots for reference.
![Uploading Screenshot from 2024-06-06 18-19-55.png…]()

**Comment by arsalanmudni2** [comment]
![Screenshot from 2024-06-06 18-20-10](https://github.com/frappe/crm/assets/168745066/50af69de-88e7-4fa6-ba85-8d4ae59f47d3)
![Screenshot from 2024-06-06 18-20-32](https://github.com/frappe/crm/assets/168745066/06a522ba-e760-4d4b-80fb-dec3a2a21da3)
![Screenshot from 2024-06-06 18-21-38](https://github.com/frappe/crm/assets/168745066/0bf8cab3-fe0f-4147-81e2-75ac13d86fe5)

**Comment by shariquerik** [comment]
@arsalanmudni2  Why are you using Desk View? you are not supposed to use it.
Try from portal and let me know if you are facing the issue

I will still look into the issue

**Comment by shariquerik** [comment]
Fixed: [fix: compare date while calculating duration](https://github.com/frappe/crm/commit/02582b6f1bad0a800480679bedf47e86738d8948)
