### ISSUE TITLE
Autocompletion of field organization inside lead is not working

### ISSUE THREAD

**Issue by the3dfox** [frappe/crm#253]
Tried frappe CRM today in frappe cloud. Unfortunately, the auto completion of the organization field inside the lead form is not working

![image](https://github.com/frappe/crm/assets/84663901/14ed4531-7e30-4e64-8c01-9314434176da)

This is a screenshot of the official frappe presentation video and the way it is supposed to work:
![image](https://github.com/frappe/crm/assets/84663901/bd3648b2-7b3b-40e3-9ccd-734ad4be58a1)

**Comment by shariquerik** [comment]
@the3dfox The screenshot you shared from the video in that the autocomplete is actually coming from chrome it is not a CRM feature.

**Comment by the3dfox** [comment]
well, I guess then I will write a FR, because I think this is essential
