### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by ajiragroup** [frappe/crm#27]
What is the estimated release date? If I am not wrong, CRM was supposed to be released with v15, isn't it ?

**Comment by shariquerik** [comment]
@ajiragroup CRM is still in WIP. As of now, there is no release date.

> CRM was supposed to be released with v15, isn't it ?

No, It was never mentioned or announced anywhere

**Comment by ajiragroup** [comment]
Oh okay, no worries. Will be waiting for release.
