### ISSUE TITLE
Change in subject in the same thread

### ISSUE THREAD

**Issue by farazk3** [frappe/crm#271]
While replying in deals, the subject is changed to default after we change the subject in the first response, and when the prospects reply the subject changes back to the default one.

1. First response I have updated the email subject as ERPNext deployment

<img width="931" alt="Screenshot 2024-07-18 at 4 01 13 PM" src="https://github.com/user-attachments/assets/ba9b132f-d5dd-4f19-a5b5-ffac4cfcc54d">
2. Subject changes back when prospecting responses as seen below screenshot, from ERPNext Deployment, changes back to name and Deal#

<img width="448" alt="Screenshot 2024-07-18 at 4 07 05 PM" src="https://github.com/user-attachments/assets/6d7711b9-933e-40b6-a461-c5aafc93999e">

**Comment by shariquerik** [comment]
I think it is not a bug, Subject will change back to default when you send new email.
