### ISSUE TITLE
save new lead

### ISSUE THREAD

**Issue by ukwuezeobinna** [frappe/crm#3]
I am trying to create a new lead but saving it doesn't seem to work. The save button doesn't work. 

![image](https://github.com/frappe/crm/assets/852830/fdf5ce59-f7c6-4669-816e-04b94d773080)

**Comment by vineyrawat** [comment]
Can you please share the console output

**Comment by shariquerik** [comment]
I have not yet added validation message, it is not working because you are typing invalid (add 10 digit number) mobile no.

**Comment by kevinbrown1980** [comment]
I'm also having this issue, the save button does not work, i've tried filling in all the fields and using a 10digit mobile number but still no luck

**Comment by rknroot** [comment]
In mobile number field add country code correctly.
for example India use +9190XXXXXX22 like this.

**Comment by niyazrazak** [comment]
User Is Automatically log out in each refresh
I think session is not storing


https://github.com/frappe/crm/assets/76736615/5e3e572c-e5a0-41b3-bdc3-41b7a4d23eac

**Comment by niyazrazak** [comment]
> User Is Automatically log out in each refresh I think session is not storing
> 
>  crm_issue.mp4

@shariquerik can you check this?

**Comment by Pithiya-Nilesh** [comment]
same issue when create new lead and session is expiered in refresh page.

![Screenshot from 2023-10-27 13-36-25](https://github.com/frappe/crm/assets/112484355/d78fd1e5-c7ee-4da0-b43d-1f24b3d775f3)

**Comment by shariquerik** [comment]
> @shariquerik can you check this?

It should be fixed now.
