### ISSUE TITLE
List view columns not displayed correctly until 'Reset to defaults' is selected

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#300]
When any new user visits the portal, the list view for Leads, Deals, Contacts, etc. shows only the 'name' and 'modified' fields by default. Selecting Columns -> Reset to defaults corrects the issue. When 'Reset to defaults' is selected, this causes a View Settings record to be created for the user, using the default columns. It seems the View Settings need to created created for the user, if they don't already exist.

**Comment by shariquerik** [comment]
fixed: https://github.com/frappe/crm/pull/305
