### ISSUE TITLE
Whatsapp chat not updated live

### ISSUE THREAD

**Issue by ajiragroup** [frappe/crm#324]
I am on v2.0.0-dev.
When sending whatsapp message to lead, the message screen does not load sent messages in RT but we have to refresh screen to see message. 

Check out: 

https://github.com/user-attachments/assets/b3710ebe-cb8f-48fc-ad75-2dbc899af45b

Also requesting, please make "type your message here" field auto focused when Whatsapp tab is active.
Also, please make the whatsapp message scroll down to latest message when Whatsapp tab is clicked.

**Comment by kumud-oa** [comment]
Is this issue still open?

**Comment by ajiragroup** [comment]
> Is this issue still open?

We hope so.

**Comment by shariquerik** [comment]
It is updating live check the video, if you are testing in local check if socketio is running

https://github.com/user-attachments/assets/a184ecd2-c910-4bcd-b6b8-6ee5a4a70721

**Comment by ajiragroup** [comment]
Yes it was in local setup. We wiped the installation currently. So, no way to check socketio. We will keep that in mind for later. Thanks.
