### ISSUE TITLE
Not working with PostgreSQL database

### ISSUE THREAD

**Issue by praveenk6491** [frappe/crm#333]
**Description:** After running the command bench new-site <site-name> --db-type postgres to create a new site with PostgreSQL, the operation fails. Following this, running bench start and attempting to create a lead results in an error as well. This issue seems to be specific to using PostgreSQL as the database, as the setup works fine with MariaDB.

**Steps to Reproduce:**

1. Run bench new-site <site-name> --db-type postgres and install crm app.
2. Run bench start.
3. Observe the error during the wizard setup process.
4. After starting the bench, attempt to create a lead in the CRM.
5. Observe the error.

The issue does not occur when using MariaDB as the database.

**Comment by shariquerik** [comment]
Currently, Postgres is not supported I will suggest you to use Mariadb
