### ISSUE TITLE
Is here any localization?

### ISSUE THREAD

**Issue by MukievMukhammad** [frappe/crm#339]
I am new here, want to contribute localization to my lang, but not found the way. Is locale came directly from frappe core?

**Comment by shariquerik** [comment]
We use Crowdin to manage translations now.
You can contribute to the translations here: [Frappe dashboard in Crowdin](https://crowdin.com/project/frappe)

**Comment by nguyenhuutinh** [comment]
I see a lot of requests for new languages. why there is not action there?
