### ISSUE TITLE
Notifications not being created for Tasks

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#364]
When scheduling a CRM Task (eg., via Lead -> Tasks -> New Task), the Task is created but no corresponding Notification is created. I've looked through the code but don't see anything that would trigger creation of a CRM Notification. CRM Tasks seem to get quietly ignored.

Tested against current develop branch.

**Comment by shariquerik** [comment]
Fixed: https://github.com/frappe/crm/pull/368
