### ISSUE TITLE
Assignments not displaying correctly in Deals / Leads list view when # of assignees > 1

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#377]
CRM: develop branch
Frappe: 15.42.0

If a Deal or Lead is assigned to more than one user, the Assignment is reflected correctly within the document view. However, the corresponding list views only show a single assignee. This is confusing for the user and all assignments should be visible in list views.

**Comment by shariquerik** [comment]
Please add some screenshots or recording to explain it better

**Comment by joshuarestivo** [comment]
Closing as I can no longer reproduce.
