### ISSUE TITLE
Currency not being displayed correctly in Deal list/kanban views

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#378]
Frappe CRM: develop branch (current)
Frappe: 15.42.0

In the Deals list and kanban view, US currency is not displaying correctly for amounts above 5-digits. It does display properly in the document Activity view. If the Amount field is set to "150000" for instance, the list and kanban views display "$1,50,000" (non-Indian currency should be N,NNN,NNN).

**Comment by shariquerik** [comment]
Fixed : https://github.com/frappe/crm/pull/487
