### ISSUE TITLE
How to set up when adding users

### ISSUE THREAD

**Issue by dgo2dance** [frappe/crm#379]
How to set up when adding users

Adding users:
Don't forget to create user accounts from the User Master section. This grants access to your CRM to team members who will be using the system.

However, the interface only has these options: How to set up?

or  How to set user types (like System User) when creating users

![image](https://github.com/user-attachments/assets/e763d4ba-cdbb-43e0-9291-56f4288b973d)

**Comment by shariquerik** [comment]
@dgo2dance try using Invite Member feature
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/cad05a14-81a7-4338-9ae9-eba007a8e950">
