### ISSUE TITLE
Rename 'Lead Owner'

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/crm#398]
The term 'Lead Owner' is confusing and potentially misleading. The fact that 'Lead Owner' and 'Assigned To' fields exist and have linked functionality creates confusion for users. The confusion is especially apparent when Lead Owner is carried forward into a Deal. 

Can we rename this field to 'Account Owner'? This would reduce the ambiguity between it and 'Assigned To'. It would also make more sense as the Lead progresses through the system. If you're integrating with ERPNext, for example, this field may need to be  updated as the account is handed off to inside sales and/or support teams. 'Account Owner' would make a lot more sense in this case. 

I realize that the field label could be updated as a band-aid but that introduces opportunity for confusion in itself.

**Comment by shariquerik** [comment]
I do not agree, It perfectly make sense to keep "Lead Owner" & "Deal Owner"
Why should I consider Lead or Deal as account. it make sense if ERPNext is part of the flow but Frappe CRM is not built for ERPNext it is a standalone app so it does not make sense to rename it to "Account Owner".
