### ISSUE TITLE
TextEditor crashes when typing @

### ISSUE THREAD

**Issue by rdr6000** [frappe/crm#399]
When i type normal text it works. But as soon as I type @ the textbox breaks and I have to refresh the page to make it work again. Mention list also does not appear. I am on latest CRM version which I pulled 2 days ago

https://github.com/user-attachments/assets/8457c5fa-552d-4985-8c66-96d5c97e8b43

**Comment by shariquerik** [comment]
I did tested in production as well as in local it is working fine

**Comment by shariquerik** [comment]
@rdr6000 Reopen if you are still facing the issue
