### ISSUE TITLE
Need Standard Code for "CRM Deal - Quick Entry" in Frappe CRM

### ISSUE THREAD

**Issue by OYbate** [frappe/crm#422]
Hi everyone,

I accidentally deleted the code for the "CRM Deal - Quick Entry" layout in Frappe CRM, and now I'm unable to create quick deals.

Could someone please provide me with the standard code for the field layout?

I'd greatly appreciate any help!

Thanks in advance.

<img width="1250" alt="Bildschirmfoto 2024-10-21 um 17 12 26" src="https://github.com/user-attachments/assets/4f738be9-60c7-491b-950a-b93bda306da0">

<img width="767" alt="Bildschirmfoto 2024-10-21 um 17 16 37" src="https://github.com/user-attachments/assets/6e7d5fa9-da16-4e7b-8c4a-5388d50c73e4">

**Comment by shariquerik** [comment]
@OYbate Go to FCRM Settings in Desk there is Restore Defaults button which will restore field layouts

**Comment by OYbate** [comment]
If I reset the CRM Fields Layout layout and reset all customizations in the Doctype CRM, the field still does not change.

<img width="1288" alt="Bildschirmfoto 2024-10-22 um 09 45 36" src="https://github.com/user-attachments/assets/94bffa19-1f2e-49f0-b64a-7e400c2ed8bd">

**Comment by shariquerik** [comment]
@OYbate Update Frappe CRM to latest version
