### ISSUE TITLE
Install Error "CircularProgressBar" is not exported by

### ISSUE THREAD

**Issue by kalungia** [frappe/crm#441]
on develop branch if you run `bench build --app crm` it returns

`[vite-plugin-pwa:build] "CircularProgressBar" is not exported by "../node_modules/frappe-ui/src/index.js", imported by "src/components/FilesUploader/FilesUploaderArea.vue".
file: /home/imbra/imbra/apps/crm/frontend/src/components/FilesUploader/FilesUploaderArea.vue:130:22
128: import FileVideoIcon from '@/components/Icons/FileVideoIcon.vue'
129: import { createToast, dateFormat, convertSize } from '@/utils'
130: import { FormControl, CircularProgressBar, createResource } from 'frappe-ui'
                           ^
131: import { ref, onMounted } from 'vue'
error during build:`

**Comment by shariquerik** [comment]
It is fixed in latest version
