### ISSUE TITLE
Some salutations out of the box?

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/crm#457]
![CleanShot 2024-12-03 at 12 07 49@2x](https://github.com/user-attachments/assets/2b7b993d-2e4d-4e48-9c83-def390286644)

Also, I am unable to create new salutations from this dialog.

**Comment by NagariaHussain** [comment]
Same for Territory

**Comment by 1ubuntuuser** [comment]
https://github.com/frappe/crm/issues/387 this issue has the fix.
