### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by princessfrombabylon99** [frappe/crm#460]
![Screenshot from 2024-12-05 23-22-24](https://github.com/user-attachments/assets/7c56bf0d-728a-457a-a50c-c9dede6fb38e)

**Comment by shariquerik** [comment]
@princessfrombabylon99 Not a bug, Make sure CRM version is compatible with frappe frameworks version
| CRM | Frappe |
|------|--------|
| develop | develop |
| main | v15 |

**Comment by princessfrombabylon99** [comment]
@shariquerik Yes, switching branch to main solved the problem.
