### ISSUE TITLE
Header Disappears on Lead Detail View Reload

### ISSUE THREAD

**Issue by SamuelHelbling** [frappe/crm#470]
**Description:**
When reloading the lead detail view, the header briefly appears before disappearing completely. This behavior prevents navigation to other tabs besides the default "Activities" tab. The issue temporarily resolves when performing specific actions, such as adding an attachment or creating a task, which causes the header to reappear and remain visible. However, the header disappears again upon reloading the page.

**Steps to Reproduce:**

1. Open a lead detail view in the application.
2. Reload the page.
3. Observe that the header briefly appears and then disappears.
![image](https://github.com/user-attachments/assets/c9745232-9d20-4800-b395-e560511ab0d7)
5. Add an attachment, note, task, etc. to the lead.
6. Note that the header reappears and remains visible.
![image](https://github.com/user-attachments/assets/26468fd9-df42-4ff9-883c-ba575dcecd4c)
8. Reload the page again.
9. Observe that the header disappears once more.
![image](https://github.com/user-attachments/assets/6f5bc7b0-47f3-4cc8-b14a-fbaafd80d38e)

**Expected Behavior:**
The header should remain visible after reloading the page, allowing seamless navigation to other tabs.

**Actual Behavior:**
The header disappears immediately after the page reloads, preventing access to any tabs other than "Activities."

**Impact:**
Limits navigation within the lead detail view.
Hinders user productivity by requiring additional steps (e.g., adding attachments or tasks) to restore header visibility temporarily.

**Comment by shariquerik** [comment]
@SamuelHelbling Is it still happening after upgrading to latest version?

**Comment by SamuelHelbling** [comment]
@shariquerik 
With version v1.27.2 the problem no longer exists.
Thank you.
