### ISSUE TITLE
Frontend build failing: `require() of ES Module` -> dependency issue?

### ISSUE THREAD

**Issue by cogk** [frappe/crm#476]
```
Running build command for crm
$ cd frontend && yarn build
$ vite build --base=/assets/crm/frontend/ && yarn copy-html-entry
failed to load config from /home/frappe/frappe-bench/apps/crm/frontend/vite.config.js
error during build:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/frappe/frappe-bench/apps/crm/node_modules/strip-ansi/index.js from /home/frappe/frappe-bench/apps/crm/node_modules/ora/index.js not supported.
Instead change the require of /home/frappe/frappe-bench/apps/crm/node_modules/strip-ansi/index.js in /home/frappe/frappe-bench/apps/crm/node_modules/ora/index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by cogk** [comment]
Re-generating the yarn.lock file seems to fix the issue @shariquerik

**Comment by oryxr** [comment]
I remove the yarn.lock but don't resolve

**Comment by cogk** [comment]
@oryxr

Maybe `bench update` is resetting the app?

This should work:

```sh
cd apps/crm
rm yarn.lock
yarn
bench build
bench migrate
```

**Comment by liamdmcgarrigle** [comment]
I'm having the same issue. 

Rebuilding the yarn file fixes it but it is effecting my ci pipeline where i wouldn't want to put a hack like that

I even tried an older version and am getting the same error

**Comment by cogk** [comment]
@liamdmcgarrigle

> Rebuilding the yarn file fixes it but it is effecting my ci pipeline where i wouldn't want to put a hack like that

If you can temporarily change the CRM repo you use in CI, my fixed version of frappe-crm is available at <https://github.com/cogk/frappe-crm> (`main` branch)

---

> I even tried an older version and am getting the same error

The error is related to non-deterministic resolution of dependencies. There is a warning in the console (https://github.com/frappe/crm/issues/476#issuecomment-2551879364).

**Comment by liamdmcgarrigle** [comment]
@cogk 
Worked great thanks
i followed your pr so i can remember to switch it back

Many thanks!
