### ISSUE TITLE
Unable to create Note inside Lead

### ISSUE THREAD

**Issue by sagar-bhogayata** [frappe/crm#56]
<img width="1497" alt="Screenshot 2024-01-17 at 11 33 59 PM" src="https://github.com/frappe/crm/assets/31538550/f0c35031-3f75-491d-af6e-777a539b9a5a">

**Comment by shariquerik** [comment]
Not able to reproduce. Can you try again with latest changes

**Comment by sagar-bhogayata** [comment]
Yes, you are right
ERPNext is Installed and CRM Note Doctype conflicting

**Comment by shariquerik** [comment]
@sagar-bhogayata For now, cannot do anything about it.
Cannot rename CRM Note both in ERPNext or CRM
Until CRM Module is not removed from ERPNext Frappe CRM will not be compatible with it

**Comment by shariquerik** [comment]
Fix: https://github.com/frappe/crm/pull/82
