### ISSUE TITLE
Bug: changing sort order removes sorting

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/crm#72]
https://github.com/frappe/crm/assets/34810212/3cb2d842-45c5-437a-b1ba-ba81454fcd93

**Comment by shariquerik** [comment]
@NagariaHussain It is not a bug, all listview has a default **orderBy** "modified desc" and I am not showing it on the **Sort** dropdown. Yes, UX is not good. Can't think of a better way to handle it🤔

**Comment by NagariaHussain** [comment]
There was a bug, which seems to be gone now. Closing...
