### ISSUE TITLE
frappe.exceptions.DuplicateEntryError: ('Module Def', 'FCRM', IntegrityError(1062, "Duplicate entry 'FCRM' for key 'PRIMARY'"))

### ISSUE THREAD

**Issue by Govind-Jangid** [frappe/crm#73]
bench install-app crm

Installing crm...
An error occurred while installing crm: ('Module Def', 'FCRM', IntegrityError(1062, "Duplicate entry 'FCRM' for key 'PRIMARY'"))
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 446, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['sca.com'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('crm',)
      force = False
      _install_app = <function install_app at 0x7fa05a3b2a20>
      filelock = <function filelock at 0x7fa05a3b0ae0>
      exit_code = 0
      site = 'sca.com'
      app = 'crm'
      err = DuplicateEntryError('Module Def', 'FCRM', IntegrityError(1062, "Duplicate entry 'FCRM' for key 'PRIMARY'"))
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    add_module_defs(name, ignore_if_duplicate=force)
      name = 'crm'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7fa05955eac0>
      sync_for = <function sync_for at 0x7fa05955fa60>
      sync_customizations = <function sync_customizations at 0x7fa05a4d4fe0>
      sync_fixtures = <function sync_fixtures at 0x7fa05955fd80>
      app_hooks = {'after_install': ['crm.install.after_install'], 'app_description': ['Kick-ass Open Source CRM'], 'app_email': ['shariq@frappe.io'], 'app_icon_route': ['/crm'], 'app_icon_title': ['CRM'], 'app_icon_url': [''], 'app_license': ['AGPLv3'], 'app_name': ['crm'], 'app_publisher': ['Frappe Technologies Pvt. Ltd.'], 'app_title': ['Frappe CRM'], 'before_install': ['crm.install.before_install'], 'before_uninstall': ['crm.uninstall.before_uninstall'], 'doc_events': {'Contact': {'validate': ['crm.api.contact.validate']}, 'ToDo': {'after_insert': ['crm.api.todo.after_insert']}, 'Comment': {'on_update': ['crm.api.comment.on_update']}}, 'override_doctype_class': {'Contact': ['crm.overrides.contact.CustomContact'], 'Email Template': ['crm.overrides.email_template.CustomEmailTemplate']}, 'website_route_rules': [{'from_route': '/crm/<path:app_path>', 'to_route': 'crm'}]}
      installed_apps = ['frappe', 'erpnext', 'payments', 'hrms', 'india_compliance', 'erpnext_telegram_integration', 'frappehr_plus', 'lending', 'raven', 'webshop', 'insights']
      before_install = 'crm.install.before_install'
      out = None
  File "apps/frappe/frappe/installer.py", line 629, in add_module_defs
    d.insert(ignore_permissions=True, ignore_if_duplicate=ignore_if_duplicate)
      app = 'crm'
      ignore_if_duplicate = False
      modules = ['FCRM']
      module = 'FCRM'
      d = <ModuleDef: FCRM>
  File "apps/frappe/frappe/model/document.py", line 297, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
      self = <ModuleDef: FCRM>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/base_document.py", line 577, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
      self = <ModuleDef: FCRM>
      ignore_if_duplicate = False
      conflict_handler = ''
      d = {'name': 'FCRM', 'creation': '2024-02-13 06:01:39.907221', 'modified': '2024-02-13 06:01:39.907221', 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 0, 'parent': None, 'parentfield': None, 'parenttype': None, 'idx': 0, 'module_name': 'FCRM', 'custom': 0, 'app_name': 'crm', 'restrict_to_domain': None, '_user_tags': None, '_comments': None, '_assign': None, '_liked_by': None, 'package': None}
      columns = ['name', 'creation', 'modified', 'modified_by', 'owner', 'docstatus', 'parent', 'parentfield', 'parenttype', 'idx', 'module_name', 'custom', 'app_name', 'restrict_to_domain', '_user_tags', '_comments', '_assign', '_liked_by', 'package']
frappe.exceptions.DuplicateEntryError: ('Module Def', 'FCRM', IntegrityError(1062, "Duplicate entry 'FCRM' for key 'PRIMARY'"))

<img width="593" alt="image" src="https://github.com/frappe/crm/assets/63184660/75bad647-c35e-4863-9be4-f32f6d906143">

**Comment by ganureddy** [comment]
me also facing the same

**Comment by nelsondurairaj** [comment]
1. uninstall the app using `bench --site site.name uninstall-app crm `
2. set as developer mode on site using `bench set-config -g developer_mode 1`
3. then install using this command `bench --site site.name install-app crm`
4. if you facing same error add --force in 3rd step `bench --site site.name install-app crm --force`

**Comment by shariquerik** [comment]
It should be fixed now
