### ISSUE TITLE
Couldn't create a new note

### ISSUE THREAD

**Issue by maiphuongfw** [frappe/crm#85]
Try to click on "Create" button after filling in the content box but can't save a new note

**Comment by shariquerik** [comment]
@maiphuongfw Cannot reproduce it.
Can you try on latest develop

**Comment by shariquerik** [comment]
Reopen if still reproducible

**Comment by maiphuongfw** [comment]
Hello Shariq

I have installed the latest version, but this bug is still showing. Still can't save a new note

**Comment by shariquerik** [comment]
Cant reproduce it, share a screen recording and also show if there is any error in console
