### ISSUE TITLE
feat: offer dropdown/auto complete for organization field in lead

### ISSUE THREAD

**Issue by the3dfox** [frappe/crm#94]
currently, the field is not dropdown/auto complete. You need to manual type in the Organization you want to link

![image](https://github.com/frappe/crm/assets/84663901/5ee794f0-48f2-4281-a439-4dde7cf1add0)

**Comment by shariquerik** [comment]
As I said in the demo and in docs, lead is only used to capture data it does not store masters
Once it is qualified you can convert to deal 
In your usecase if you need organization as a master then you should skip lead and create deal instead

**Comment by the3dfox** [comment]
ahh thanks for clarifying. Sounds logical indeed.
